#!/usr/bin/env ruby

require 'pinkbike/pod/downloader'
require 'optparse'

# Parse arguments
options = {}
ARGV << '-h' if ARGV.empty? # Show the help message if no command line arguments are provided
OptionParser.new do |opts|
  opts.on('-o', '--output-directory OUTPUT_DIRECTORY', 'The directory where downloaded images should be stored') do |v|
    options[:output_dir] = v
    unless Dir.exists?(v)
      Dir.mkdir(v)
    end
  end
  opts.on('-k', '--twitter-consumer-key TWITTER_CONSUMER_KEY') do |v|
    options[:twitter_consumer_key] = v
  end
  opts.on('-s', '--twitter-consumer-secret TWITTER_CONSUMER_SECRET') do |v|
    options[:twitter_consumer_secret] = v
  end
  opts.on('-t', '--twitter-access-token TWITTER_ACCESS_TOKEN') do |v|
    options[:twitter_access_token] = v
  end
  opts.on('-a', '--twitter-access-secret TWITTER_ACCESS_SECRET') do |v|
    options[:twitter_access_secret] = v
  end
end.parse!

# Check that we've been provided with the required arguments
%w{TWITTER_CONSUMER_KEY TWITTER_CONSUMER_SECRET TWITTER_ACCESS_TOKEN TWITTER_ACCESS_SECRET OUTPUT_DIR}.each do |key|
  next unless options[key.downcase.to_sym].nil?
  raise Exception, "You must set ENV[#{key}] or provide --#{key.downcase.gsub(/_/,'-')} #{key}" if ENV[key].nil?
end

Pinkbike::Pod::Downloader.run(options)
